name: Run lint and jest test
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run lint and jest test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Jest
        run: npm run test
